{
  "openapi": "3.0.0",
  "info": {
    "title": "Velocity Network Foundation Push Gateway Protocol",
    "version": "1.0",
    "description": "The Velocity Network Foundation Push Gateway Protocol that wallet providers must implement"
  },
  "servers": [],
  "paths": {
    "/push": {
      "post": {
        "summary": "Push a new notification",
        "responses": {
          "204": {
            "description": "No Content"
          },
          "400": {
            "description": "Bad Request"
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "operationId": "get-push",
        "description": "Creates a new push notification. Send again if you dont receive a response",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "id": {
                    "type": "string",
                    "description": "generate an id to support deduplication"
                  },
                  "pushToken": {
                    "type": "string",
                    "description": "the push token for this group of devices"
                  },
                  "data": {
                    "type": "object",
                    "description": "Data is used for data that is not private to be sent. Coming soon - support for encrypted data that is only accessible once the app boots.",
                    "required": [
                      "notificationType"
                    ],
                    "properties": {
                      "notificationType": {
                        "type": "string",
                        "enum": [
                          "CredentialRevoked",
                          "CredentialReplaced",
                          "NewOffersReady",
                          "NoOffersFound",
                          "PresentationVerified"
                        ],
                        "description": "the notification type"
                      },
                      "issuer": {
                        "type": "string",
                        "description": "the issuer's DID"
                      },
                      "exchangeId": {
                        "type": "string",
                        "description": "the exchange id to which this push corresponds to"
                      },
                      "serviceEndpoint": {
                        "type": "string",
                        "format": "uri",
                        "description": "the service endpoint to find out more information about this message. Should be verified on the Issuers DID Document"
                      },
                      "credentialTypes": {
                        "type": "string",
                        "description": "the credential types of the offers or credentials"
                      },
                      "credentialId": {
                        "type": "string",
                        "description": "the credential id being revoked or replaced"
                      },
                      "replacementCredentialType": {
                        "type": "string",
                        "description": "the credential type of the new credential when the notificationType=CredentialReplaced"
                      }
                    }
                  },
                  "encryptedData": {
                    "type": "string",
                    "description": "e2e encrypted version of `data`. holder app should send it under `data.encrypted` property"
                  },
                  "notification": {
                    "type": "object",
                    "additionalProperties": false,
                    "description": "the notification to be displayed by the default push message handler (eg. fcm)",
                    "required": [
                      "title",
                      "body"
                    ],
                    "properties": {
                      "title": {
                        "type": "string"
                      },
                      "body": {
                        "type": "string"
                      },
                      "image": {
                        "type": "string"
                      }
                    }
                  },
                  "message": {
                    "type": "string",
                    "description": "An optional message. The wallet developer should have a default message that it uses for each notification type. An issuer may send a message with more specific information. The wallet developer can choose to use this message instead"
                  }
                },
                "required": [
                  "id",
                  "pushToken",
                  "data",
                  "notification"
                ]
              },
              "examples": {
                "Revocation Example": {
                  "value": {
                    "id": "8wMT_9O0mZLck8JELBDV6",
                    "pushToken": "62",
                    "data": {
                      "exchangeId": "62afffc898ca4264f5d7352d",
                      "notificationType": "CredentialRevoked",
                      "issuer": "did:ion:EiBbvWpBHPql_2W9sObr4vPFl9k9InEDYOEDXvPPRDRyBg",
                      "credentialId": "did:velocity:v2:6GiWWYRSys1U2j5I6gqq7olyJw0M3aqZcuHsST0",
                      "credentialTypes": [
                        "LicenseV1.0"
                      ],
                      "count": 1
                    }
                  }
                },
                "Replacement Example": {
                  "value": {
                    "id": "8wMT_9O0mZLck8JELBDV7",
                    "pushToken": "63",
                    "data": {
                      "exchangeId": "62afffc898ca4264f5d7352d",
                      "notificationType": "CredentialRevoked",
                      "issuer": "did:ion:EiBbvWpBHPql_2W9sObr4vPFl9k9InEDYOEDXvPPRDRyBg",
                      "credentialId": "did:velocity:v2:6GiWWYRSys1U2j5I6gqq7olyJw0M3aqZcuHsST1",
                      "credentialTypes": [
                        "EmploymentCurrentV1.1"
                      ],
                      "replacementCredentialType": [
                        "EmploymentPastV1.1"
                      ],
                      "count": 1
                    }
                  }
                },
                "New Offers Ready": {
                  "value": {
                    "id": "8wMT_9O0mZLck8JELBDV8",
                    "pushToken": "64",
                    "data": {
                      "exchangeId": "62afffc898ca4264f5d7352d",
                      "notificationType": "NewOffersReady",
                      "issuer": "did:ion:EiBbvWpBHPql_2W9sObr4vPFl9k9InEDYOEDXvPPRDRyBg",
                      "serviceEndpoint": "https://agent.example.com",
                      "credentialTypes": [
                        "EmploymentCurrentV1.1"
                      ],
                      "count": 1
                    }
                  }
                },
                "No Offers Found": {
                  "value": {
                    "id": "8wMT_9O0mZLck8JELBDV9",
                    "pushToken": "65",
                    "data": {
                      "exchangeId": "62afffc898ca4264f5d7352d",
                      "notificationType": "NoOffersFound",
                      "issuer": "did:ion:EiBbvWpBHPql_2W9sObr4vPFl9k9InEDYOEDXvPPRDRyBg",
                      "serviceEndpoint": "https://agent.example.com"
                    }
                  }
                }
              }
            }
          },
          "description": "The message that should be sent."
        }
      },
      "parameters": []
    }
  },
  "components": {
    "securitySchemes": {
      "API Key": {
        "type": "http",
        "scheme": "bearer"
      }
    }
  }
}